name: Astro Build Test

on: [pull_request]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 #v6
        with:
          node-version: 22

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run the Astro build command
      - name: Build project
        run: npm run build
